name: SimpleRanks
main: com.tommustbe12.simpleranks.Simpleranks
author: TomMustBe12
website: https://tommustbe12.com
version: 2.3
api-version: 1.20
softdepend: [PlaceholderAPI]
commands:
  rank:
    description: Manage player ranks
    usage: /rank <create|delete|give|importanttext|setdefault|bracketcolor> [args]
    permission: simpleranks.use
    aliases: [r]
permissions:
  simpleranks.use:
    description: Allows use of rank commands
    default: op